AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Telegram bot on AWS Lambda (Webhook) - NotificadorV16_bot

Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - arm64
    Timeout: 10
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        TELEGRAM_API_BASE: https://api.telegram.org
        MAX_SUBSCRIPTIONS: "50"

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OpsTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BotDlqQueue.QueueName
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          TELEGRAM_WEBHOOK_SECRET: !Ref TelegramWebhookSecret
          SUBSCRIPTIONS_TABLE: !Ref SubscriptionsTable
          OPS_TABLE: !Ref OpsTable
          BOT_DLQ_URL: !Ref BotDlqQueue
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            Path: /webhook
            Method: POST

  PollerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: poller.lambda_handler
      Timeout: 25
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OpsTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DsqlSecretArn
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PollerDlqQueue.QueueName
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          SUBSCRIPTIONS_TABLE: !Ref SubscriptionsTable
          OPS_TABLE: !Ref OpsTable
          DSQL_SECRET_ARN: !Ref DsqlSecretArn
          DGT_XML_URL: https://nap.dgt.es/datex2/v3/dgt/SituationPublication/datex2_v36.xml
          NOTIFY_TTL_SECONDS: "86400"
          METRICS_NAMESPACE: NotificadorV16Bot
          POLLER_LOCK_TTL_SECONDS: "55"
          HISTORY_CLOSE_MISSING_AFTER_SECONDS: "180"
          POLLER_DLQ_URL: !Ref PollerDlqQueue
      Events:
        EveryMinute:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Enabled: true


  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  OpsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  BotDlqQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  PollerDlqQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  AlertsTopic:
    Type: AWS::SNS::Topic

  PollerErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Poller reported errors (custom EMF metric poller_errors).
      Namespace: NotificadorV16Bot
      MetricName: poller_errors
      Dimensions:
        - Name: Service
          Value: PollerFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic

  PollerNoNotificationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Events parsed but no notifications sent (possible mapping/subscription issue).
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Metrics:
        - Id: mParsed
          MetricStat:
            Metric:
              Namespace: NotificadorV16Bot
              MetricName: events_parsed
              Dimensions:
                - Name: Service
                  Value: PollerFunction
            Period: 300
            Stat: Sum
          ReturnData: false
        - Id: mDeliverable
          MetricStat:
            Metric:
              Namespace: NotificadorV16Bot
              MetricName: notify_deliverable_targets
              Dimensions:
                - Name: Service
                  Value: PollerFunction
            Period: 300
            Stat: Sum
          ReturnData: false
        - Id: mSent
          MetricStat:
            Metric:
              Namespace: NotificadorV16Bot
              MetricName: notifications_sent
              Dimensions:
                - Name: Service
                  Value: PollerFunction
            Period: 300
            Stat: Sum
          ReturnData: false
        - Id: e1
          Expression: IF(mParsed>0 AND mDeliverable>0 AND mSent==0, 1, 0)
          Label: ParsedButNoSent
          ReturnData: true
      AlarmActions:
        - !Ref AlertsTopic

  TelegramBotLambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: TelegramBotFunction Lambda Errors > 0.
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref TelegramBotFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic

  PollerLambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: PollerFunction Lambda Errors > 0.
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref PollerFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertsTopic

  LogRetentionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: log_retention.lambda_handler
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:PutRetentionPolicy
              Resource: "*"
      Environment:
        Variables:
          LOG_RETENTION_DAYS: "90"

  SetLogRetention:
    Type: Custom::SetLogRetention
    Properties:
      ServiceToken: !GetAtt LogRetentionFunction.Arn
      LogGroupNames:
        - !Sub "/aws/lambda/${TelegramBotFunction}"
        - !Sub "/aws/lambda/${PollerFunction}"
      RetentionInDays: 90

Parameters:
  TelegramToken:
    Type: String
    NoEcho: true
    Description: Telegram bot token (from BotFather)
  TelegramWebhookSecret:
    Type: String
    NoEcho: true
    Description: Secret token used to validate X-Telegram-Bot-Api-Secret-Token header
  DsqlSecretArn:
    Type: String
    Description: Secrets Manager ARN with Aurora DSQL connection JSON (host, port, dbname, username, password)

Outputs:
  HttpApiUrl:
    Description: Base URL for the HTTP API
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  SubscriptionsTableName:
    Description: DynamoDB table for chat subscriptions
    Value: !Ref SubscriptionsTable

  OpsTableName:
    Description: DynamoDB table for ops/state/settings/dedupe
    Value: !Ref OpsTable

  AlertsTopicArn:
    Description: SNS topic for alarms (subscribe your email/SMS/Slack to receive alerts)
    Value: !Ref AlertsTopic

  BotDlqQueueUrl:
    Description: SQS DLQ for webhook bot errors
    Value: !Ref BotDlqQueue

  PollerDlqQueueUrl:
    Description: SQS DLQ for poller errors
    Value: !Ref PollerDlqQueue

