AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Telegram bot on AWS Lambda (Webhook) - NotificadorV16_bot

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        TELEGRAM_API_BASE: https://api.telegram.org
        MAX_SUBSCRIPTIONS: "50"

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          TELEGRAM_WEBHOOK_SECRET: !Ref TelegramWebhookSecret
          SUBSCRIPTIONS_TABLE: !Ref SubscriptionsTable
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            Path: /webhook
            Method: POST

  PollerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: poller.lambda_handler
      Timeout: 25
      ReservedConcurrentExecutions: 1
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          SUBSCRIPTIONS_TABLE: !Ref SubscriptionsTable
          DGT_XML_URL: https://nap.dgt.es/datex2/v3/dgt/SituationPublication/datex2_v36.xml
          NOTIFY_TTL_SECONDS: "86400"
          METRICS_NAMESPACE: NotificadorV16Bot
      Events:
        EveryMinute:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Enabled: true

  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Parameters:
  TelegramToken:
    Type: String
    NoEcho: true
    Description: Telegram bot token (from BotFather)
  TelegramWebhookSecret:
    Type: String
    NoEcho: true
    Description: Secret token used to validate X-Telegram-Bot-Api-Secret-Token header

Outputs:
  HttpApiUrl:
    Description: Base URL for the HTTP API
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  SubscriptionsTableName:
    Description: DynamoDB table for chat subscriptions
    Value: !Ref SubscriptionsTable

